### ISSUE TITLE
Generating MSL shaders programmatically

### ISSUE THREAD

**Issue by kskyten** [akb825/ModularShaderLanguage#1]
Awesome work, MSL looks great! I'm interested in generating MSL shaders from Julia. How would I go about creating the AST and compiling MSL programmatically in C++?

**Comment by akb825** [comment]
MSL doesn't have an AST of its own as it is a meta-language built on top of GLSL. Parsing has two main phases:
1. The code is passed through a C++ pre-processor (boost::wave) and converted into tokens.
2. Fragments of GLSL are extracted from the tokens to be processed for the individual shaders. This primarily consists of filtering (based on the [[_stage_]] tags) and handling a few specialized cases by hand.

A translation from Julia would technically be possible if you were to output the extended GLSL syntax that MSL parses, either saving to a temporary file or providing a stream (e.g. `std::stringstream`) and passing it to the `compile()` function for the target you want to use.

Is your goal for compute or graphics? MSL supports compute shaders, but within the context of a graphics pipeline for use in graphics APIs such as Vulkan, OpenGL, and Metal. This distinction is important, since compute shaders run in a graphics pipeline don't support the full feature set of pure GPGPU compute such as CUDA and OpenCL.

If your goal is compute rather than graphics, a better fit may be [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator). If you can translate Julia to LLVM IR, SPIRV-LLVM-Translator should allow you to convert it to SPIR-V that can be run in OpenCL.

**Comment by kskyten** [comment]
My goal is to produce shaders for graphics. GPU computing is actually fairly well supported in Julia. Perhaps it is better to use something like https://github.com/graphitemaster/glsl-parser and extend it with Julia.

**Comment by akb825** [comment]
In that case, you will probably be better off with [glslang](https://github.com/KhronosGroup/glslang), which is the official GLSL parser. It would offer the most complete language support, and already supports parsing a different language (HLSL) into the same AST.
