### ISSUE TITLE
Compatibility with GLSLify

### ISSUE THREAD

**Issue by jarble** [akb825/ModularShaderLanguage#2]
There is another module system for GLSL called [GLSLify](https://github.com/glslify/glslify), so I want to  know if the Modular Shader language will be compatible with it. Will it possible to use modules from the Modular Shader Language with GLSLify, or vice-versa?

**Comment by akb825** [comment]
Looking at GLSLify, the modules seem to be at a different level. GLSLify uses modules at the code level, allowing you to import the modules for writing your code. By contrast, MSL uses modules at the final output level: it unifies the different shader stages into pipelines, and allows for multiple pipelines to be combined into a single logical package.

Given how they are fundamentally different, I don't see how they would be able to work with each-other. It is possible to extract the GLSL (assuming you're using a GLSL target) from a compiled MSL module, but they will be fully-contained shaders, including the main() function. My guess is that this won't play nicely with GLSLify. Similarly, while MSL supports importing code through a C pre-processor, my guess is that the GLSLify modules aren't set up so they could just be #included into the source you're writing. Additionally, since the output of GLSLify appears to be a fully-contained GLSL file, that wouldn't really work with MSL since it adds extra syntax to define shader pipelines.

I hope this answers your question.
