### ISSUE TITLE
error: variable 'line' set but not used

### ISSUE THREAD

**Issue by yurivict** [akb825/ModularShaderLanguage#7]
Compilation fails:
```
/wrkdirs/usr/ports/graphics/msl/work/ModularShaderLanguage-1.7.1/Compile/src/Preprocessor.cpp:85:14: error: variable 'line' set but not used [-Werror,-Wunused-but-set-variable]
        std::size_t line = e.line_no();
                    ^
1 error generated.
```

msl-1.7.1
clang 15.0.7
FreeBSD 13.1

**Comment by akb825** [comment]
@yurivict Thanks, I have pushed up a fix for the 1.7.2 release.

Since I have your attention, have you seen my comments for the [Cuttlefish test failures](https://github.com/akb825/Cuttlefish/issues/17) you posted a couple months back? I wasn't able to reproduce the issue when building and running the tests straight from the repository ona FreeBSD VM. I expect that there's an issue where the original code was moved or deleted and the tests aren't able to find the expected input files, but I need more information on how you're running them to investigate further.
